### ISSUE TITLE
[SUGGESTION] 3D layouts support

### ISSUE THREAD

**Issue by fnrcum** [PQguanfang/MythicTotem#4]
I'm imagining being able to create 3d totems (having width, height and depth) that can spawn things. This could even be used to "emulate" multi-block structures (by spawning a MM/IA entity that would be a immovable object like a piece of furniture as well as bigger mobs (Imagine a redstone monstrosity golem.

Let me know if this is even possible :D

The layers i'm imagining being calculated from the bottom up meaning `layer1` or `layer0` or whatever number you start the layer list with, is the bottom layer and everything goes on top of it.

I can also see a few potential conditions that can be added such as:
1. `uniform_totem: true/false` # refers to all the layers being the same size
2. `prev_layer_bigger: true/false` # refers to each layer being smaller or at least equal to the layer bellow it. `uniform_totem` would overwrite this condition.

```yaml
totems:
  test:
    layout3d:
      layer1:
         - 'AAA'
         - 'BBB'
         - 'CCC'
      layer2:
         - 'AAA'
         - 'BBB'
         - 'CCC'
      layer3:
         - 'AAA'
         - 'BBB'
         - 'CCC'
      layer4:
         - 'AAA'
         - 'BBB'
         - 'CCC'
    explains:
      A: 'minecraft:stone'
      B: 'minecraft:end_stone'
      C: 'minecraft:netherrack'
    actions:
      - 'message: Hello!'
      - 'mythicmobs_spawn: SkeletalKnight'
    conditions:
      - 'none'
    disappear: true
```
